### PR TITLE
first version of the action

### PR DESCRIPTION
**Pull request by galyfray**
The code hasn't been tested. This means that the 1.0 won't be released won't after this PR.

- Created a base docker file based on python's docker image.
- Created the base of the action, which takes only one required argument: `filename`.
-  Created the base action.yml

### CODE REVIEW

**Comment by galyfray** [comment]
The failing of the Exemple action is expected.

**Review by mnoel2000 — COMMENTED** [review]
Good that seems to work fine.

**Review by mnoel2000 — COMMENTED** [review]
Good spelling

**Review by mnoel2000 — APPROVED** [review]
Good that seems to work fine

**Pull request merged**
